apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iped-jobs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iped-jobs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iped-jobs
    spec:
      containers:
      - image: setecrs/iped_jobs:1.0.0
        imagePullPolicy: IfNotPresent
        name: iped-jobs
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /root/.kube/
          name: kubeconf
          readOnly: true
      volumes:
      - name: kubeconf
        secret:
          defaultMode: 420
          secretName: kubectl
