help:
	@echo "install_tools_localhost           installs pip packages, and k3d and argocd CLI on localhost"

install_tools_localhost:
	ansible-playbook install_tools_localhost.yml

PHONY: help install_tools_localhost
